# Generated by Django 4.0.1 on 2022-03-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=24)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
    ]
