# Generated by Django 4.0.1 on 2022-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
